### ISSUE TITLE
Can't Parse Malc0de Blacklist

### ISSUE THREAD

**Issue by Sachiru** [WaterByWind/edgeos-bl-mgmt#1]
http://malc0de.com/bl/IP_Blacklist.txt

For some reason, adding the blacklist above inflates the generated IP set so that it cannot be created even when MaxElem is set to something ridiculous like a million entries or so.

**Comment by WaterByWind** [comment]
The comment marker used by MalC0de was not properly filtered, which in turned confused IPset and resulted in a fatal error.  This has now been corrected.

I have also added this URL to the default list (commented) as well.
