### ISSUE TITLE
Firewall rules not accepted

### ISSUE THREAD

**Issue by jimmyeao** [WaterByWind/edgeos-bl-mgmt#11]
I pretty new to this, but trying to commit the example fw rules gives me this?

sav[ firewall ipv6-name wan-dmz-6 ]
Firewall config error: 'action' must be defined

e[ firewall name wan-dmz-4 ]
Firewall config error: 'action' must be defined

[ firewall name wan-lan-4 ]
Firewall config error: 'action' must be defined
                                                                                                                      [ firewall name wan-self-4 ]
Firewall config error: 'action' must be defined

[ firewall ipv6-name wan-self-6 ]
Firewall config error: 'action' must be defined

[ firewall ipv6-name wan-lan-6 ]
Firewall config error: 'action' must be defined

**Comment by WaterByWind** [comment]
A firewall rule must have at least an action defined, which is the reason this message was returned upon trying to commit the configuration.  Adding a a 'drop' action to each of the rules will correct this.

The README was missing the 'action' definition, but this has been corrected (as an example)
