### ISSUE TITLE
Silence sed warning

### ISSUE THREAD

**Issue by mklxd** [WaterByWind/edgeos-bl-mgmt#12]
To silence the following error message from sed, apply the patch below:
`sed: character class syntax is [[:space:]], not [:space:]`

Patch:
```
diff --git a/updBlackList.sh b/updBlackList.sh
index d04caca..246b9d0 100755
--- a/updBlackList.sh
+++ b/updBlackList.sh
@@ -475,7 +475,7 @@ doProcess4()
     cat ${flBlockList} | \
         sed -e '/^[;#]/d' \
             -e '/ERROR/d' \
-            -e '/[:\::]/d' \
+            -e '/[\:\::]/d' \
             -e 's/ .*//g' \
             -e 's#//.*##g' \
             -e 's/[^0-9,.,/]*//g' \
```

**Comment by WaterByWind** [comment]
I do not receive this error.  Are you running this on your edgerouter or elsewhere?  On  edgeos 'sed' is actually the busybox implementation.

**Comment by mklxd** [comment]
Yes. I get this error running on ER4 under 2.0 beta-3

**Comment by WaterByWind** [comment]
Ah - You probably mean 2.0.0-_alpha_.3.   FYI that is actually not a beta and is actually a _still in-development alpha_ that is currently still undergoing significant changes.  I do not see the error on alpha-2, for instance.

Once that version moves into a beta (it has not yet) I will be testing there but until then it is still far too early to try to chase as the platform is still in too great of a state of change.

I'll keep this open to track until then.

**Comment by mklxd** [comment]
You’re right, it’s alpha3. UBNT upgraded to Debian stretch on this version.

**Comment by WaterByWind** [comment]
I've pushed this minor update (finally).  It has been working on both 1.x and 2.x releases for me and it just took me finding the 30 seconds to publish it. . .
