### ISSUE TITLE
Suggesting additional ban list sources

### ISSUE THREAD

**Issue by eohrnberger** [WaterByWind/edgeos-bl-mgmt#16]
http://blocklist.greensnow.co/greensnow.txt
http://charles.the-haleys.org/ssh_dico_attack_hdeny_format.php/hostsdeny.txt
http://osint.bambenekconsulting.com/feeds/c2-ipmasterlist.txt
http://talosintel.com/feeds/ip-filter.blf
http://www.binarydefense.com/banlist.txt
https://www.badips.com/get/list/any/2?age=30d

**Comment by WaterByWind** [comment]
Thanks!  These have now been added, disabled/commented to be individually enabled as appropriate.

Note that you'll want to be sure to use the latest updBlackList.sh which has been updated as well to accommodate their formatting.
