### ISSUE TITLE
Config question

### ISSUE THREAD

**Issue by jimmyeao** [WaterByWind/edgeos-bl-mgmt#17]
More a question than an issue.
I have this setup as per the readme however it is not 100% clear to me, should the FW policies (e.g. WAN - LAN ) have interfaces defined?
same question for Nets4-BlackList etc, should they have a network defined? (currently empty)

Many thanks :)

**Comment by vincent1890** [comment]
same question

**Comment by blisstik** [comment]
Would like to bump this question. Also, I'm pinging some of these IPs and still getting reply. Is this inbound only?

**Comment by WaterByWind** [comment]
The firewall policies should be applied to relevant interfaces, yes.

Or more precisely you would add a rule to your existing policy for the appropriate direction on the appropriate interface.  For instance,  create a rule in your WAN_IN policy that uses the noted groups, and do the same for your WAN_LOCAL.

The rule should have a match on the network group with action 'drop'.
