### ISSUE TITLE
No longer works on USG

### ISSUE THREAD

**Issue by mvnixon** [WaterByWind/edgeos-bl-mgmt#6]
USG has moved to a new labelling system for firewall groups - instead of using the actual name they use 'hashed names'. Would be great to fix this somehow...

**Comment by WaterByWind** [comment]
Unfortunately I don't have a USG to test with currently so won't be able to help with this right now.  I'll keep this open in case that changes.

**Comment by WaterByWind** [comment]
UniFi Security Gateways (USGs) include a supported IDS/IPS solution now.
