### ISSUE TITLE
IP Range won't install - ER-X

### ISSUE THREAD

**Issue by hedrinjt** [WaterByWind/edgeos-bl-mgmt#7]
I have an ER-X and following the install options for IPRange I had an error:

```
package architecture (mips) does not match system (mipsel)
Errors were encountered while processing:
 iprange_1.0.3+ds-1_mips.deb
```

Checked out that repository and there was a mipsel out there so I downloaded that:
`curl -O http://http.us.debian.org/debian/pool/main/i/iprange/iprange_1.0.3+ds-1_mipsel.deb`

Just wondering if your script will use this version and wanted you to be aware of it.

**Comment by hedrinjt** [comment]
Reading your comments closer you already provide this information.  Apologies.

**Comment by WaterByWind** [comment]
Yes - mipsel (rather than mips) should be used for an ER-X.  I plan to provide a little more detail when I move the notes to a wiki page instead, where it really should be.
