### ISSUE TITLE
Can't confirm rulesets are applied

### ISSUE THREAD

**Issue by krisclarkdev** [WaterByWind/edgeos-bl-mgmt#9]
Can you provide steps to confirm that the new rulesets have been applied?

EdgeRouter PoE v1.9.7+hotfix.3

**Comment by WaterByWind** [comment]
I'm not sure exactly to which part this is referring.  You would create the needed firewall rules yourself via EdgeOS configuration so checking that configuration will confirm the rules are in place.

To verify if the actual lists are being populated you would use 'ipset' via CLI on the router:
`sudo ipset -L Nets4-BlackList | wc -l` and `sudo ipset -L Nets6-BlackList | wc -l` for the IPv4 and IPv6 lists, respectively.  That will show the count of entries in each list, +7.  You can view the actual contents by omiting the `| wc -l` but the lists are typically _very_ long.

**Comment by cd-rum** [comment]
Do they ever appear in the GUI? `sudo ipset...` returns the count, but the GUI says 0.

**Comment by WaterByWind** [comment]
No the count of members will never show in the GUI as it is not aware of the actual ipset contents.  The GUI is based on the edgeos configuration.
